# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pool:
  name: "default"

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo y | "C:\Users\oscal\AppData\Local\Android\Sdk/cmdline-tools/latest/bin/sdkmanager" --licenses
  displayName: 'Android Lisanslarını Kabul Et (Windows)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: assembleDebug'
    publishJUnitResults: false

- task: DownloadSecureFile@1
  name: keystoreFile
  inputs:
    secureFile: 'BirdHolderKeystore.jks'
    retryCount: 2

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    sign: true
    keystoreFile: '$(keystoreFile.secureFilePath)'
    keystorePass: '$(KEYSTORE_PASSWORD)'
    keyAlias: '$(KEY_ALIAS)'
    keyPass: '$(KEY_PASSWORD)'
    zipalign: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'APK'
