# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  name: "default"

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
  displayName: 'Android Lisanslarını Kabul Et'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assemble$(buildConfiguration)'
    publishJUnitResults: false

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'APK'
