pool:
  name: "default"

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo y | "C:\Users\oscal\AppData\Local\Android\Sdk/cmdline-tools/latest/bin/sdkmanager" --licenses
  displayName: 'Android Lisanslarını Kabul Et (Windows)'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksign: true            # ya da alias’ı olan sign: true
    keystoreFile: 'BirdHolderKeystore.jks'   # Secure files’daki dosya adı
    keystorePass: '$(KEYSTORE_PASSWORD)'
    keystoreAlias: '$(KEY_ALIAS)'
    keyPass: '$(KEY_PASSWORD)'
    zipalign: true


- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'APK'

- task: GooglePlayRelease@4
  inputs:
    authType: 'JsonFile'
    serviceAccountKey: 'catholder_serviceaccount.json'
    applicationId: 'com.oscaliskan.catholder'
    action: 'SingleApk'
    apkFile: '**/*.apk'
    track: 'internal'
    changeLogFile: 'test release'
    releaseName: 'Release Test'